[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.9.1"
reqwasm = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4"
web-sys = "0.3.55"
yew = "0.19.3"
